# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Gufeng Liu's Personal Website"
description              : "M.S. in Business Analytics at Columbia University | Data Analyst Intern | Rock Keyboard Player"
repository               : "GeoffLiu3/GeoffLiu.github.io"
google_scholar_stats_use_cdn : true

# google analytics
# google_analytics_id      :  # 暂时注释掉 Google Analytics 设置

# SEO Related
# google_site_verification :  # 暂时注释掉 SEO 验证设置
# bing_site_verification   :
# baidu_site_verification  :

# Site Author
author:
  name             : "Gufeng Liu"
  avatar           : "images/avatar.png"  # 确保您头像文件路径正确
  bio              : "M.S. in Business Analytics at Columbia University and Tsinghua University"
  location         : "New York, NY"
  # employer         : "Apple Inc."  # 如果需要显示当前工作公司信息，可以取消注释
  # pubmed           : 
  # googlescholar    : "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID"  # 填写 Google Scholar 链接
  email            : "gl2915@columbia.edu"
  linkedin         : "https://www.linkedin.com/in/gufeng-liu/"
  github           : "GeoffLiu3"
  # instagram        :
  # orcid            :
  # pinterest        :
  # stackoverflow    :
  # twitter          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: America/New_York # 根据您的位置设置为 New York 时区

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  # - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development